server:
  port: 8080
# Configuration Spring
spring:
  # Configuration profile
  profiles:
    active: dev
  # Configuration application
  application:
    name: control-academico
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# Configuration Logging
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
