spring:
  datasource:
    url: jdbc:mysql://localhost:3306/control_academico
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dev
    password: dev

  # Configuration Liquibase
  liquibase:
    contexts: dev
    parameters:
      datetime_type: DATETIME
      liquibase.secureParsing: false

  jpa:
    hibernate:
      ddl-auto: validate