spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/control_academico
    username: dev
    password: dev
  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    contexts: prod
    parameters:
      datetime_type: TIMESTAMP WITHOUT TIME ZONE

# Configuration SpringDoc - Desactiva documentación en el ambiente de producción
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false