spring:
  datasource:
    url: jdbc:mysql://localhost:3306/control_academico
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dev
    password: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
